services:
  Cnd\DddMakerBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Cnd\DddMakerBundle\Maker\MakeCqrsFromEntity:
    tags: [ 'maker.command' ]

  Cnd\DddMakerBundle\Maker\Cqrs\MakeQueryFromEntity:
    tags: [ 'maker.command' ]

  Cnd\DddMakerBundle\Maker\Cqrs\MakeCommandFromEntity:
    tags: [ 'maker.command' ]


  Cnd\DddMakerBundle\Maker\Cqrs\MakeValueObjectsDomain:
    tags: [ 'maker.command' ]
