services:
  Cnd\DddMakerBundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

  Cnd\DddMakerBundle\Maker\MakeCqrsFromEntity:
    tags: [ 'maker.command' ]
